name: GitPages - Update on every push and once a day

on:
  push:
  schedule: 
    - cron: '0 2 * * *'        
  workflow_dispatch:       

jobs:
  poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r .gitpage/requirements.txt

      - name: Run the poller
        run: python .gitpage/update.py
        env:
          GITHUB_TOKEN: "${{ secrets.FOR_POLLING }}"
          GITHUB_USERNAME: "${{ vars.USER_FOR_POLLING }}"
          GITHUB_REPO: "${{ github.repository }}"

      - name: Mirroring the README 
        run: python .gitpage/mirror.py
        env:
          GITHUB_TOKEN: "${{ secrets.FOR_POLLING }}"
          GITHUB_USERNAME: "${{ vars.USER_FOR_POLLING }}"
          GITHUB_REPO: "${{ github.repository }}"   
          RUN_MIRROR: "${{ vars.RUN_MIRROR }}"

